export default function data() {
  return [
    {
      id: 1,
      slug: "official-web-site-of-the-president-of-uzbekistan",
      title: "Headquarters.one.title",
      description: "Headquarters.one.description",
      img: "/images/gerb.png",
      link: "Headquarters.one.link",
      seo: {
        title: "Headquarters.one.seo.title",
        description: "Headquarters.one.seo.description",
        keywords: "Headquarters.one.seo.keywords",
        image: "/images/Headquarters/www.president.uz.png",
      },
    },
    {
      id: 2,
      slug: "legislative-chamber-of-the-oliy-majlis-of-the-republic-of-uzbekistan",
      title: "Headquarters.two.title",
      description: "Headquarters.two.description",
      img: "/images/gerb.png",
      link: "Headquarters.two.link",
      seo: {
        title: "Headquarters.two.seo.title",
        description: "Headquarters.two.seo.description",
        keywords: "Headquarters.two.seo.keywords",
        image: "/images/Headquarters/parliament.gov.uz.png",
      },
    },
    {
      id: 3,
      slug: "senate-of-the-oliy-majlis-of-the-republic-of-uzbekistan",
      title: "Headquarters.three.title",
      description: "Headquarters.three.description",
      img: "/images/gerb.png",
      link: "Headquarters.three.link",
      seo: {
        title: "Headquarters.three.seo.title",
        description: "Headquarters.three.seo.description",
        keywords: "Headquarters.three.seo.keywords",
        image: "/images/Headquarters/senat.uz.png",
      },
    },
    {
      id: 4,
      slug: "government-of-the-republic-of-uzbekistan",
      title: "Headquarters.four.title",
      description: "Headquarters.four.description",
      img: "/images/gerb.png",
      link: "Headquarters.four.link",
      seo: {
        title: "Headquarters.four.seo.title",
        description: "Headquarters.four.seo.description",
        keywords: "Headquarters.four.seo.keywords",
        image: "/images/Headquarters/gov.uz.png",
      },
    },
    {
      id: 5,
      slug: "constitutional-court-of-the-republic-of-uzbekistan",
      title: "Headquarters.five.title",
      description: "Headquarters.five.description",
      img: "/images/gerb.png",
      link: "Headquarters.five.link",
      seo: {
        title: "Headquarters.five.seo.title",
        description: "Headquarters.five.seo.description",
        keywords: "Headquarters.five.seo.keywords",
        image: "/images/Headquarters/www.konstsud.uz.png",
      },
    },
    {
      id: 6,
      slug: "supreme-court-of-the-republic-of-uzbekistan",
      title: "Headquarters.six.title",
      description: "Headquarters.six.description",
      img: "/images/gerb.png",
      link: "Headquarters.six.link",
      seo: {
        title: "Headquarters.six.seo.title",
        description: "Headquarters.six.seo.description",
        keywords: "Headquarters.six.seo.keywords",
        image: "/images/Headquarters/sud.uz.png",
      },
    },
    {
      id: 7,
      slug: "general-prosecutors-office-of-the-republic-of-uzbekistan",
      title: "Headquarters.seven.title",
      description: "Headquarters.seven.description",
      img: "/images/gerb.png",
      link: "Headquarters.seven.link",
      seo: {
        title: "Headquarters.seven.seo.title",
        description: "Headquarters.seven.seo.description",
        keywords: "Headquarters.seven.seo.keywords",
        image: "/images/Headquarters/www.prokuratura.uz.png",
      },
    },
  ];
}
